exports.auth = require('./api/auth');
// exports.baskets = require('./api/baskets');
// exports.customers = require('./api/customers');
exports.products = require('./api/products');
// exports.orders = require('./api/orders');
// exports.sites = require('./api/sites');
// exports.stores = require('./api/stores');
// exports.orchestration = require('./api/orchestration');
// exports.transforms = require('./transforms');
